# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim

# Install the project into `/app`
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

COPY s2-self-cert/pyproject.toml .
COPY s2-self-cert/uv.lock .

# Install the project's dependencies using the lockfile and settings
COPY packages /packages
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project


COPY s2-self-cert /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"
RUN whoami
ENV PYTHONPATH="/app/src"

# Change ownership and permissions of config.yaml
RUN chown -R root:root /app/
RUN chmod -R 755 /app/

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

CMD ["python3", "/app/src/s2selfcert/main.py"]