---

services:
  s2-self-cert-server:
    build:
      dockerfile: ./docker/Dockerfile.server
    command: fastapi run /app/src/main.py --host 0.0.0.0 --port 8001
    ports:
      - ${PORT:-8001}:8001
    volumes:
      - ./s2-self-cert-server/data:/app/data
      # - ./s2-self-cert-server/src:/app/src
      # - ./packages:/packages
    environment:
      SERVER_KEY_PATH: "/app/data/server_key.pem"
      KEYS_STORAGE_PATH: "/app/data/keys.json"
    healthcheck:
      test: curl http://localhost:8001/healthcheck || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s
