[project]
name = "s2-self-certification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.11.3",
    "s2-python",
    "watchdog>=6.0.0",
    "websockets>=13.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "mypy>=1.15.0",
    "pyyaml>=6.0.2",
]

[tool.uv.sources]
s2-python = { path = "../s2-python", editable = true }
