[project]
name = "s2-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-multipart>=0.0.20",
    "connectivity",
    "test-suites",
]


[tool.uv.sources]
test-suites = { path = "../packages/test-suites", editable = true }
connectivity = { path = "../packages/connectivity", editable = true }
