
device_details:
  name: Some Device
  manufacturer: ABCD
mode: testing
connection:
  mode: client
  uri: ws://127.0.0.1:8001/ws
  host: 127.0.0.1
  port: 8000
control_types:
  no_selection: null
  pebc: 
    enabled : true
    status_update_frequency: 10
  frbc:
    enabled: true