
device_details:
  name: Some Device
  manufacturer: ABCD
mode: testing
certification:
  uri: ws://s2-self-cert-server:8000/
connection:
  mode: server
  host: 0.0.0.0
  port: 8000
  uri: ws://localhost:8001/backend/cem/cem1/rm/pv1/ws
control_types:
  no_selection: null
  pebc: 
    enabled : true
  frbc:
    enabled: true