[project]
name = "s2-self-cert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["s2-python", "test-suites"]

[tool.uv.sources]
test-suites = { path = "../packages/test-suites", editable = true }
s2-python = { path = "../packages/s2-python", editable = true }
